// AI Stream – Mock-Daten für MVP-Entwicklung
import type { Conversation, Message, AIAgent, Automation, Mailbox, SavedFilter } from '@/types'

const TENANT_ID = '00000000-0000-0000-0000-000000000001'
const NOW = new Date().toISOString()

export const mockMailboxes: Mailbox[] = [
  { id: 'mb-1', tenant_id: TENANT_ID, name: '#1 Main', color: '#3B82F6', position: 1 },
  { id: 'mb-2', tenant_id: TENANT_ID, name: '#2 Sales', color: '#10B981', position: 2 },
  { id: 'mb-3', tenant_id: TENANT_ID, name: '#3 Support', color: '#F59E0B', position: 3 },
  { id: 'mb-4', tenant_id: TENANT_ID, name: '#4 Recruiting', color: '#8B5CF6', position: 4 },
  { id: 'mb-5', tenant_id: TENANT_ID, name: '#5 Marketing', color: '#EF4444', position: 5 },
]

export const mockSavedFilters: SavedFilter[] = [
  { id: 'sf-1', tenant_id: TENANT_ID, name: 'New Leads', emoji: '😊', config: {}, position: 0 },
  { id: 'sf-2', tenant_id: TENANT_ID, name: 'VIP Customer', emoji: '🏆', config: {}, position: 1 },
]

const mainMailbox: Mailbox = { id: 'mb-1', tenant_id: TENANT_ID, name: '#1 Main', color: '#3B82F6', position: 1 }
const salesMailbox: Mailbox = { id: 'mb-2', tenant_id: TENANT_ID, name: '#2 Sales', color: '#10B981', position: 2 }
const supportMailbox: Mailbox = { id: 'mb-3', tenant_id: TENANT_ID, name: '#3 Support', color: '#F59E0B', position: 3 }

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    tenant_id: TENANT_ID,
    mailbox_id: 'mb-1',
    channel: 'whatsapp',
    status: 'open',
    contact_name: 'Lisa Jackson',
    contact_identifier: '+4917627545331',
    assigned_to: 'me',
    last_message_at: '2025-09-12T16:27:00Z',
    is_read: false,
    is_starred: false,
    preview_text: 'Perfect. Thank you for your quick response...',
    mailbox: mainMailbox,
    created_at: '2025-09-12T16:20:00Z',
  },
  {
    id: 'conv-2',
    tenant_id: TENANT_ID,
    mailbox_id: 'mb-1',
    channel: 'whatsapp',
    status: 'open',
    contact_name: 'Mika Hally',
    contact_identifier: '+4917612345678',
    assigned_to: undefined,
    last_message_at: '2025-09-11T16:22:00Z',
    is_read: true,
    is_starred: true,
    preview_text: 'Hi Mika, how can we assist you today?',
    mailbox: mainMailbox,
    created_at: '2025-09-11T16:20:00Z',
  },
  {
    id: 'conv-3',
    tenant_id: TENANT_ID,
    mailbox_id: 'mb-2',
    channel: 'email',
    status: 'open',
    contact_name: 'Thomas Müller',
    contact_identifier: 'thomas@mueller.de',
    assigned_to: undefined,
    last_message_at: '2025-09-11T10:15:00Z',
    is_read: false,
    is_starred: false,
    preview_text: 'Ich würde gerne mehr über eure Enterprise-Preise erfahren...',
    mailbox: salesMailbox,
    created_at: '2025-09-11T10:00:00Z',
  },
  {
    id: 'conv-4',
    tenant_id: TENANT_ID,
    mailbox_id: 'mb-3',
    channel: 'whatsapp',
    status: 'later',
    contact_name: 'Anouar Springer',
    contact_identifier: '+4915112345678',
    assigned_to: 'me',
    last_message_at: '2025-09-10T14:00:00Z',
    is_read: true,
    is_starred: false,
    preview_text: 'Vielen Dank für die Rückmeldung, ich melde mich dann...',
    mailbox: supportMailbox,
    created_at: '2025-09-10T13:00:00Z',
  },
  {
    id: 'conv-5',
    tenant_id: TENANT_ID,
    mailbox_id: 'mb-1',
    channel: 'whatsapp',
    status: 'done',
    contact_name: 'Sarah Weber',
    contact_identifier: '+4917699887766',
    assigned_to: 'me',
    last_message_at: '2025-09-09T11:30:00Z',
    is_read: true,
    is_starred: true,
    preview_text: 'Alles geklärt, vielen Dank für die schnelle Hilfe!',
    mailbox: mainMailbox,
    created_at: '2025-09-09T11:00:00Z',
  },
  {
    id: 'conv-6',
    tenant_id: TENANT_ID,
    mailbox_id: 'mb-2',
    channel: 'email',
    status: 'open',
    contact_name: 'Jonas Becker',
    contact_identifier: 'jonas@becker.de',
    assigned_to: undefined,
    last_message_at: '2025-09-08T09:00:00Z',
    is_read: false,
    is_starred: false,
    preview_text: 'Können wir einen Demo-Termin vereinbaren?',
    mailbox: salesMailbox,
    created_at: '2025-09-08T08:50:00Z',
  },
]

export const mockMessages: Record<string, Message[]> = {
  'conv-1': [
    {
      id: 'msg-1',
      tenant_id: TENANT_ID,
      conversation_id: 'conv-1',
      role: 'customer',
      content: 'Hi 📦 I have a question regarding my order',
      channel: 'whatsapp',
      is_note: false,
      sent_at: '2025-09-12T16:23:00Z',
    },
    {
      id: 'msg-1b',
      tenant_id: TENANT_ID,
      conversation_id: 'conv-1',
      role: 'customer',
      content: 'This is how the package arrived to us. The contents are damaged. What should I do now?',
      channel: 'whatsapp',
      is_note: false,
      sent_at: '2025-09-12T16:23:30Z',
    },
    {
      id: 'msg-2',
      tenant_id: TENANT_ID,
      conversation_id: 'conv-1',
      role: 'agent',
      content: '@Alexander Farr Could you please take a look at this? 😊',
      channel: 'whatsapp',
      is_note: true,
      sent_at: '2025-09-12T16:24:00Z',
    },
    {
      id: 'msg-3',
      tenant_id: TENANT_ID,
      conversation_id: 'conv-1',
      role: 'agent',
      content: 'Hello Lisa, a colleague will get in touch with you soon and explain how we will proceed from here 😊',
      channel: 'whatsapp',
      is_note: false,
      sent_at: '2025-09-12T16:25:00Z',
    },
    {
      id: 'msg-4',
      tenant_id: TENANT_ID,
      conversation_id: 'conv-1',
      role: 'customer',
      content: 'Perfect. Thank you for your quick response. Unfortunately, the package was left outside and it rained...',
      channel: 'whatsapp',
      is_note: false,
      sent_at: '2025-09-12T16:27:00Z',
    },
  ],
  'conv-2': [
    {
      id: 'msg-5',
      tenant_id: TENANT_ID,
      conversation_id: 'conv-2',
      role: 'ai',
      content: 'Hallo! Ich bin der AI Stream Support-Agent — wie kann ich Ihnen heute helfen?',
      channel: 'whatsapp',
      is_note: false,
      sent_at: '2025-09-11T16:20:00Z',
    },
    {
      id: 'msg-6',
      tenant_id: TENANT_ID,
      conversation_id: 'conv-2',
      role: 'customer',
      content: 'Hi Mika, ich hätte eine Frage zu meinem Account.',
      channel: 'whatsapp',
      is_note: false,
      sent_at: '2025-09-11T16:22:00Z',
    },
  ],
  'conv-3': [
    {
      id: 'msg-7',
      tenant_id: TENANT_ID,
      conversation_id: 'conv-3',
      role: 'customer',
      content: 'Guten Tag, ich würde gerne mehr über eure Enterprise-Preise erfahren. Wir haben ca. 50 Mitarbeiter.',
      channel: 'email',
      is_note: false,
      sent_at: '2025-09-11T10:15:00Z',
    },
  ],
  'conv-4': [
    {
      id: 'msg-8',
      tenant_id: TENANT_ID,
      conversation_id: 'conv-4',
      role: 'customer',
      content: 'Vielen Dank für die Rückmeldung, ich melde mich dann nächste Woche.',
      channel: 'whatsapp',
      is_note: false,
      sent_at: '2025-09-10T14:00:00Z',
    },
  ],
  'conv-5': [
    {
      id: 'msg-9',
      tenant_id: TENANT_ID,
      conversation_id: 'conv-5',
      role: 'customer',
      content: 'Alles geklärt, vielen Dank für die schnelle Hilfe!',
      channel: 'whatsapp',
      is_note: false,
      sent_at: '2025-09-09T11:30:00Z',
    },
  ],
  'conv-6': [
    {
      id: 'msg-10',
      tenant_id: TENANT_ID,
      conversation_id: 'conv-6',
      role: 'customer',
      content: 'Hallo, können wir einen Demo-Termin vereinbaren? Wir sind sehr interessiert an AI Stream.',
      channel: 'email',
      is_note: false,
      sent_at: '2025-09-08T09:00:00Z',
    },
  ],
}

export const mockAgents: AIAgent[] = []

export const mockAutomations: Automation[] = [
  {
    id: 'auto-1',
    tenant_id: TENANT_ID,
    name: 'Außerhalb Öffnungszeiten',
    type: 'outside_hours',
    flow_config: { nodes: [], edges: [] },
    status: 'draft',
    runs: 0,
    tasks: 0,
    folder: 'My Automations',
    created_by_name: 'Mika Hally',
    created_at: '2025-11-26T14:14:20Z',
    updated_at: '2025-11-26T14:14:20Z',
  },
  {
    id: 'auto-2',
    tenant_id: TENANT_ID,
    name: 'KI-Agent antwortet immer',
    type: 'always',
    flow_config: { nodes: [], edges: [] },
    status: 'active',
    runs: 142,
    tasks: 318,
    folder: 'My Automations',
    created_by_name: 'Mika Hally',
    created_at: '2025-11-26T11:53:15Z',
    updated_at: NOW,
  },
]
